<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VirtualWardrobe.Application\VirtualWardrobe.Application.csproj" />
    <ProjectReference Include="..\VirtualWardrobe.Domain\VirtualWardrobe.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
