// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VirtualWardrobe.Infrastructure.Persistence;

#nullable disable

namespace VirtualWardrobe.Infrastructure.Migrations
{
    [DbContext(typeof(VirtualWardrobeDbContext))]
    partial class VirtualWardrobeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.MediaAssetRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FileSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.TemplateSlotDefinitionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("template_slot_definitions", (string)null);
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.TemplateSlotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("FulfilledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfilled_at_utc");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WardrobeItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("wardrobe_item_id");

                    b.Property<Guid?>("WishlistItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_item_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("WardrobeItemId")
                        .IsUnique()
                        .HasFilter("wardrobe_item_id IS NOT NULL");

                    b.HasIndex("UserId", "Category");

                    b.HasIndex("UserId", "TemplateId");

                    b.ToTable("template_slots", (string)null);
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_template_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("google_subject");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ActiveTemplateId");

                    b.HasIndex("Email");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.WardrobeItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BodyImageAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("body_image_asset_id");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<Guid?>("CareTagImageAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_tag_image_asset_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("size");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Category");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("wardrobe_items", (string)null);
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.WardrobeTemplateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("wardrobe_templates", (string)null);
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.WishlistExternalLinkRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Label")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<Guid>("WishlistItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("wishlist_item_id");

                    b.HasKey("Id");

                    b.HasIndex("WishlistItemId");

                    b.HasIndex("WishlistItemId", "Url")
                        .IsUnique();

                    b.ToTable("wishlist_external_links", (string)null);
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.WishlistItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<Guid?>("ConvertedWardrobeItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_wardrobe_item_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("InspirationImageAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspiration_image_asset_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PurchasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("target_price");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("wishlist_items", (string)null);
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.MediaAssetRecord", b =>
                {
                    b.HasOne("VirtualWardrobe.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithMany("MediaAssets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.TemplateSlotDefinitionRecord", b =>
                {
                    b.HasOne("VirtualWardrobe.Infrastructure.Persistence.Entities.WardrobeTemplateRecord", "Template")
                        .WithMany("SlotDefinitions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.TemplateSlotRecord", b =>
                {
                    b.HasOne("VirtualWardrobe.Infrastructure.Persistence.Entities.WardrobeTemplateRecord", "Template")
                        .WithMany("TemplateSlots")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualWardrobe.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.HasOne("VirtualWardrobe.Infrastructure.Persistence.Entities.WardrobeTemplateRecord", "ActiveTemplate")
                        .WithMany()
                        .HasForeignKey("ActiveTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveTemplate");
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.WardrobeItemRecord", b =>
                {
                    b.HasOne("VirtualWardrobe.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.WishlistExternalLinkRecord", b =>
                {
                    b.HasOne("VirtualWardrobe.Infrastructure.Persistence.Entities.WishlistItemRecord", "WishlistItem")
                        .WithMany("ExternalLinks")
                        .HasForeignKey("WishlistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WishlistItem");
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.WishlistItemRecord", b =>
                {
                    b.HasOne("VirtualWardrobe.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.WardrobeTemplateRecord", b =>
                {
                    b.Navigation("SlotDefinitions");

                    b.Navigation("TemplateSlots");
                });

            modelBuilder.Entity("VirtualWardrobe.Infrastructure.Persistence.Entities.WishlistItemRecord", b =>
                {
                    b.Navigation("ExternalLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
