# SSH key pair generated by Lightsail. The private key is a sensitive output that
# the bring-up runbook stores as a GitHub Actions Secret for deploy.yml.

resource "aws_lightsail_key_pair" "app" {
  name = "vw-app-key"
}
